name: bing-wall
version: '2.3'
summary: Bing Wallpaper of the day to Gnome Desktop
description: |
  Little powerful utility brings Bing Wallpaper of the day to your desktop with ease of few clicks, Allows download wallpaper with clicks and save them to accessible directory.
  
grade: stable
confinement: strict
icon: snap/gui/icon.png
base: core20
compression : lzo

architectures:
  - build-on: amd64
    run-on: amd64
    
environment:
  SNAP_DESKTOP_RUNTIME: $SNAP/qt5-core20
  
apps:
  bing-wall:
    command: bin/desktop-launch $SNAP/usr/bin/bing-wall
    autostart: BingWall.desktop
    environment:
       DISABLE_WAYLAND: 1
       IS_SNAP: 1
       NO_AT_BRIDGE: 1
    desktop: usr/share/applications/bingwall.desktop
    plugs:
        - home
        - unity7
        - network
        - opengl
        - x11
        - desktop
        - gsettings
        - desktop-legacy
        - network-manager
        - network-observe
        - network-bind
        - wayland

plugs:
  gsettings:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  qt5-core20:
    interface: content
    target: $SNAP/qt5-core20
    default-provider: qt5-core20

parts:
   desktop-qt5-build:
     plugin: nil
     build-packages:
       - build-essential
       - qtbase5-dev
       - dpkg-dev
     
   build-src:
     source-type: git
     source: https://github.com/keshavbhatt/BingWall.git
     source-subdir: src/
     plugin: qmake
     after: [desktop-qt5-build]
     override-build: |
            snapcraftctl build
            sed -i 's|Icon=.*|Icon=${SNAP}/meta/gui/icon.png|g' ${SNAPCRAFT_PART_SRC}/src/bingwall.desktop
            mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/
            cp -rf ${SNAPCRAFT_PART_SRC}/src/bingwall.desktop ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/bingwall.desktop

   desktop-launch:
     plugin: nil
     source: https://github.com/keshavbhatt/qt5-core20.git
     after: [build-src]
     override-build: |
            snapcraftctl build
            mkdir -p ${SNAPCRAFT_PART_INSTALL}/bin/
            cp -rf ${SNAPCRAFT_PART_SRC}/snap_launcher/bin/desktop-launch ${SNAPCRAFT_PART_INSTALL}/bin/
