name: bing-wall
version: '3.0'
summary: Bing Wallpaper of the day to Gnome Desktop
description: |
  Little powerful utility brings Bing Wallpaper of the day to your desktop with ease of few clicks, Allows download wallpaper with clicks and save them to accessible directory.
icon: snap/gui/icon.png

base: core24
grade: stable
confinement: strict
compression : lzo

layout:
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /var/cache/fontconfig:
    bind: $SNAP_DATA/var/cache/fontconfig

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
    
environment:
  SNAP_DESKTOP_RUNTIME: $SNAP/qt6-core24
  
apps:
  bing-wall:
    command-chain: [bin/desktop-launch]
    command: usr/bin/bing-wall
    autostart: BingWall.desktop
    environment:
       IS_SNAP: 1
       NO_AT_BRIDGE: 1
    desktop: usr/share/applications/bingwall.desktop
    plugs:
        - desktop
        - desktop-legacy
        - gsettings
        - home
        - opengl
        - unity7
        - x11
        - network
        - wayland

plugs:
  gsettings:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  qt6-core24:
    interface: content
    target: $SNAP/qt6-core24
    default-provider: qt6-core24

parts:
   build-src:
     source: .
     source-subdir: src/
     plugin: nil
     build-packages:
        - build-essential
        - qt6-base-dev
     override-build: |
            craftctl default
            qmake6 PREFIX=${CRAFT_PART_INSTALL}/usr src
            make -j4
            make install

            sed -i 's|Icon=.*|Icon=${SNAP}/meta/gui/icon.png|g' ${CRAFT_PART_SRC}/src/bingwall.desktop
            mkdir -p ${CRAFT_PART_INSTALL}/usr/share/applications/
            cp -rf ${CRAFT_PART_SRC}/src/bingwall.desktop ${CRAFT_PART_INSTALL}/usr/share/applications/bingwall.desktop
   launchers:
     plugin: dump
     source: command-chain/
     build-attributes: [no-patchelf]
     organize:
       '*': bin/
   #todo get command-chain-from content snap source
